  const styles = {
  container: {
    maxWidth: "500px",
    margin: "50px auto",
    padding: "20px",
    borderRadius: "10px",
    background: "#f9f9f9",
    boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
    textAlign: "center",
  },
  heading: {
    marginBottom: "20px",
    color: "#333",
  },
  form: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
  },
  input: {
    flex: 1,
    padding: "10px",
    border: "1px solid #ccc",
    borderRadius: "5px",
  },
  button: {
    margin: "5px" ,
    padding: "10px 15px",
    border: "none",
    borderRadius: "5px",
    background: "#007bff",
    color: "#fff",
    cursor: "pointer",
  },
  saveButton: {
    marginLeft: "5px",
    padding: "5px 10px",
    background: "#28a745",
    border: "none",
    borderRadius: "5px",
    color: "#fff",
    cursor: "pointer",
  },
  cancelButton: {
    marginLeft: "5px",
    padding: "5px 10px",
    background: "#6c757d",
    border: "none",
    borderRadius: "5px",
    color: "#fff",
    cursor: "pointer",
  },
  editButton: {
    marginLeft: "10px",
    padding: "5px 10px",
    background: "#ffc107",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
  },
  deleteButton: {
    marginLeft: "5px",
    padding: "5px 10px",
    background: "#dc3545",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    color: "#fff",
  },
  searchButton: {
    marginLeft: "5px",
    padding: "5px 10px",
    border: "none",
    borderRadius: "5px",
    background: "#28a745",   // green
    color: "#fff",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "bold",
    transition: "background 0.3s ease",
},
  list: {
    listStyle: "none",
    padding: 0,
  },
  item: {
    padding: "10px",
    marginBottom: "8px",
    background: "#fff",
    borderRadius: "5px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  statusButton: {
    margin: "5px" ,
    padding: "10px 15px",
    border: "none",
    borderRadius: "5px",
    // background: "#007bff",
    color: "#000",
    cursor: "pointer",
  },
};

export default styles;